[advisories]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
